Repository hoprnet/hopr-ethereum, pull requests merged in 2020-09, with the labels that each got.

#111 ✨ implement solkol & xdai migrations
  .github/workflows/build-test-and-release.yaml
  .github/workflows/create-release.yml
  .github/workflows/deployment.yaml
  contracts/HoprChannels.sol
  contracts/HoprFaucet.sol
  contracts/HoprToken.sol
  faucet/package.json
  faucet/pages/api/mint.ts
  faucet/utils/ethereum.ts
  faucet/yarn.lock
  migrations/1_hopr_token.js
  migrations/2_hopr_channels.js
  migrations/3_hopr_minter.js
  migrations/4_hopr_faucet.js
  package.json
  scripts/addresses.ts
  scripts/operations/migrate.ts
  scripts/operations/test.ts
  test/HoprChannels.test.ts
  test/HoprFaucet.test.ts
  test/utils/Ticket.ts
  truffle-config.js
  truffle-networks.js
  yarn.lock
Labels: needs-review

#114 Update symbol
  package.json
  test/HoprToken.test.ts
Labels: Minor Version, needs-review

#115 Bugfix/version
  .yarnrc
  package.json
Labels: Minor Version

#117 version-bump
  package.json
Labels: Minor Version

#118 Enhancement/improve maintainability
  contracts/HoprChannels.sol
  test/HoprChannels.test.ts
Labels: Patch Version

#120 Bugfix/luck encoding
  contracts/HoprChannels.sol
Labels: Patch Version

#121 ✨ xdai support
  .github/workflows/build-test-and-release.yaml
Labels: needs-review
